apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: quarkus-helloworld_web
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
  restartPolicy: Always
